feat: add navigation #PT-419
intive/patronage22_lublin_js_cms pull request #11
Opened 2022-02-17 16:16 UTC by Misiorny

Finish navigation

2022-02-18 12:20 UTC, patrykomiotek requested changes

2022-02-18 12:20 UTC, patrykomiotek commented on src/components/Menu/Menu.tsx
> +            <h1 >Menu</h1 >
unnecessary space `<h1>` 

we can also use 2 spaces for indents in code instead of 4

2022-02-18 12:20 UTC, patrykomiotek commented on src/components/Layout/AuthLayout/index.tsx
> +        <Route exact path="/" render={() => <AuthPage />}/>
render is a special props used with "render props pattern". We should use below sytnax:

```jsx
<Route exact path="/">
  <AuthPage />
</Route>
```

or:
```jsx
<Route exact path="/" component={AuthPage}>
  <AuthPage />
</Route>
```

2022-02-18 12:41 UTC, Misiorny commented on src/components/Menu/Menu.tsx
> +            <h1 >Menu</h1 >
Not mine file. I fix it.

2022-02-18 12:41 UTC, Misiorny commented on src/components/Layout/AuthLayout/index.tsx
> +        <Route exact path="/" render={() => <AuthPage />}/>
Not mine file.

2022-02-18 14:07 UTC, dblach-intive requested changes

2022-02-18 14:07 UTC, dblach-intive commented on src/components/Menu/Menu.tsx
> +        <h1>Menu</h1>
remove h1 tag

2022-02-18 14:07 UTC, dblach-intive commented on src/components/Navigation/NavItem.tsx
> +import {Link,  ListItem} from '@mui/material/'
remove / form the end

2022-02-18 14:07 UTC, dblach-intive commented on src/components/Navigation/NavItemList.tsx
> +import {List} from '@mui/material/';
remove slash from end

2022-02-18 14:11 UTC, Misiorny commented on src/components/Menu/Menu.tsx
> +        <h1>Menu</h1>
Without any tag? Or delete all with Menu word?

2022-02-22 08:46 UTC, dblach-intive requested changes
why you added a table to this commit ? This Pr is only for menu, remove all Table components

2022-02-22 12:17 UTC, closed without merging