Feature/pt 475
intive/patronage22_lublin_js_cms pull request #20
Opened 2022-02-22 13:52 UTC by DmytroTarasiuk

After submitting form we get our new product in a database. You should have you server run.

2022-02-23 09:03 UTC, dblach-intive requested changes
Looks good, could you rebase with newest main? you will have left menu, add a new page add product and put this form inside separate page

2022-02-23 09:04 UTC, dblach-intive commented on src/components/lib/categories.ts
> +  const categories = axios(`${CONSTANTS.URL}/api/categories`, {
we can return here

2022-02-23 09:04 UTC, dblach-intive commented on src/components/lib/products.ts
> +  const products = axios(`${CONSTANTS.URL}/api/products/getAllProducts`, {
we can return here

2022-02-23 09:06 UTC, dblach-intive commented on src/pages/Dashboard.tsx
> +    getProducts(token)
I think that we can assign token inside getProducts function in lib, we will have clean code here, token shoudl be pass in every api call function inside

2022-02-23 09:07 UTC, dblach-intive commented on src/pages/Dashboard.tsx
> +  const addProductRequest = async (product: any) => {
this request should be inside lib and then just import it in here

2022-02-23 09:08 UTC, dblach-intive commented on src/components/Product/AddProduct.tsx
> +      const { data } = await axios.post(
create separate function in lib folder and then import it in here

2022-02-23 09:08 UTC, dblach-intive commented on src/components/Product/AddProduct.tsx
> +      const config = {
this should be inside new function

2022-02-23 09:09 UTC, dblach-intive commented on src/components/Product/AddProduct.tsx
> +    onAddProduct(product);
all these states shoudl be in stored in one object const initialState = {category: "", title: "".......} - we will have only one useState hook with object

2022-02-23 09:11 UTC, dblach-intive commented on src/components/lib/products.ts
> +const getProducts = async (token: string | null) => {
token snould be provided in here from context - we dont want to receive it from outside every time

2022-02-23 09:12 UTC, dblach-intive commented on src/components/Product/AddProduct.tsx
> +  const statuses = [
we can store it in enum in ts file

2022-02-23 09:14 UTC, dblach-intive commented on src/components/Product/AddProduct.tsx
> +        for (const key in data) {
hm why do we need this for ? getCategories should return array of objects ready for inject into state

2022-02-23 09:17 UTC, dblach-intive commented on src/pages/Dashboard.tsx
> +  }, [token]);
without token only []

2022-02-24 10:47 UTC, DmytroTarasiuk commented on src/components/Product/AddProduct.tsx
> +    onAddProduct(product);
In my opinion, it's better to keep a single useState approach because we have different types of data and here might be a problem while  defining hadleChange function

2022-02-24 11:10 UTC, DmytroTarasiuk commented on src/pages/Dashboard.tsx
> +    getProducts(token)
In this case we would need to create a custom hook. React Hook "useContext" is called in function "getProducts" that is neither a React function component nor a custom React Hook function

2022-02-24 11:29 UTC, DmytroTarasiuk commented on src/pages/Dashboard.tsx
> +  const addProductRequest = async (product: any) => {
yes but we don't have a product parameter as it goes from AddProduct component

2022-02-25 11:08 UTC, closed without merging