feature page 404 #PT-1000
intive/patronage22_lublin_js_cms pull request #24
Opened 2022-02-22 16:49 UTC by Misiorny

2022-02-22 19:52 UTC, Misiorny commented
I don't change ErrorPageInfo.tsx to index.tsx due to make another error infos in future

2022-02-23 15:50 UTC, patrykomiotek requested changes
We shouldn't change lines we're not using. `For example Layout/index.tsx` or `Navigation/index.tsx` contains lines changed probably by IDE auto-formatting.
For error page we can use: 

```jsx
<Route path="*"><ErrorPageInfo></Route/>
```

2022-02-25 12:13 UTC, dblach-intive requested changes

2022-02-25 12:13 UTC, dblach-intive commented on src/components/Layout/index.tsx
> +          <Route path='*'><ErrorPageInfo/></Route>
`<Route path='*' component={ErrorPageInfo}/>` this will be like the others

2022-02-25 12:13 UTC, dblach-intive commented on src/components/Errors/ErrorPageInfo.tsx
> +        display: 'flex',
put this inline styles into separate file module css
Remove red background, leave only "404 Page not found"

2022-02-25 12:13 UTC, dblach-intive commented on src/components/Router/Router.tsx
> +        <Route component={AuthGuard(Layout)}/>
are we missing path='*' here ?

2022-02-25 12:56 UTC, Misiorny commented on src/components/Layout/index.tsx
> +          <Route path='*'><ErrorPageInfo/></Route>
Patryk suggest as you can see up, and you suggest something different. Could you speak with Patryk and determine correct version?

2022-02-25 12:58 UTC, Misiorny commented on src/components/Router/Router.tsx
> +        <Route component={AuthGuard(Layout)}/>
According to article which you send me was without path.

2022-02-25 14:56 UTC, dblach-intive commented on src/components/Router/Router.tsx
> +        <Route component={AuthGuard(Layout)}/>
ok

2022-02-25 14:56 UTC, dblach-intive commented on src/components/Layout/index.tsx
> +          <Route path='*'><ErrorPageInfo/></Route>
okay its the same, but another notation - use as u prefer

2022-02-25 15:14 UTC, Misiorny commented on src/components/Router/Router.tsx
> +        <Route component={AuthGuard(Layout)}/>
Here, without path looks more readable.

2022-02-28 14:49 UTC, dblach-intive submitted a review, later dismissed

2022-02-28 15:55 UTC, dblach-intive requested changes
./src/components/Layout/index.tsx
Module not found: Can't resolve '../Header/Header' in '/Users/daniel.blach/patronage/patronage22_lublin_js_cms/src/components/Layout'

2022-03-01 08:53 UTC, dblach-intive submitted a review, later dismissed

2022-03-02 10:34 UTC, dblach-intive approved these changes

2022-03-02 11:13 UTC, patrykomiotek approved these changes
looks legit after changes

2022-03-02 11:20 UTC, merged