add products list page
intive/patronage22_lublin_js_cms pull request #25
Opened 2022-02-22 20:26 UTC by Edyta2801

2022-02-23 08:43 UTC, dblach-intive requested changes
Looks good but, we have already our custom Table in: https://github.com/intive/patronage22_lublin_js_cms/tree/main/src/components/Table

Could you use our table because we will be using this one i all tables in our app

2022-02-23 09:47 UTC, dblach-intive commented
Please keep commits name and prs convention - you can find info in tracker

2022-02-23 15:25 UTC, patrykomiotek commented on package.json
> +    "moment": "^2.29.1",
moment is no longer developed anymore. We can use https://date-fns.org/ instead

2022-02-23 15:25 UTC, patrykomiotek commented on src/components/Layout/index.tsx
> +          <Route exact path="/products" render={() => <Products />} /></Switch>
it's render props pattern and is not needed here. We can write:

```jsx
<Route exact path="/products" /><Products /></Route/>
```

or 

```jsx
<Route exact path="/products" component={Products} /></Route/>
```

2022-03-01 09:16 UTC, dblach-intive requested changes
![Zrzut ekranu 2022-03-1 o 10 14 09](https://user-images.githubusercontent.com/69142210/156140382-1acfd119-6917-41c3-89e5-df4b8204fc58.png)

2022-03-03 11:47 UTC, dblach-intive requested changes

2022-03-03 11:47 UTC, dblach-intive commented on src/components/Layout/index.tsx
> +          <Route exact path="/products" /> <Products /><Route/>
can we use the same as in other places ? ->  <Route exact path={....} component={....} />

2022-03-03 11:47 UTC, dblach-intive commented on src/components/Table/EditButton.tsx
> +const EditButton: React.FC<Props> = ({ children, onClick }) => {
we need to pass ID product here

2022-03-03 11:47 UTC, dblach-intive commented on src/components/Table/EditButton.tsx
> +    <Button variant="text" color="primary" size="small" onClick={onClick} href={`/products/ID_PRODUCT`}>
Id product props should be added not ID_PRODUCT

2022-03-03 11:47 UTC, dblach-intive commented on src/components/Table/ProductsRow.tsx
> +        <EditButton onClick={() => console.log('Button clicked')}>Edit</EditButton>
Create new route for edited product and redirect it on onCLick -> "product/edit/Id_produktu

2022-03-04 09:02 UTC, dblach-intive requested changes

2022-03-04 09:02 UTC, dblach-intive commented on src/components/Table/EditButton.tsx
> +    <Button variant="text" color="primary" size="small" onClick={onClick}
here you can use onClick={() => history.push(`/product/edit/${productId}`)}

2022-03-04 09:02 UTC, dblach-intive commented on src/components/Table/EditButton.tsx
> +const EditButton: React.FC<Props> = ({ children, onClick }) => {
prop productId here or id its up to u

2022-03-04 09:02 UTC, dblach-intive commented on src/components/Table/ProductsRow.tsx
>  const ProductsRow: React.FC<CustomRowProps> = ({ product }) => {
you can destructure here {id, title, price, published, createdAt}

2022-03-04 09:02 UTC, dblach-intive commented on src/components/Table/ProductsRow.tsx
> +let {productId} = useParams<{productId?:any}>();
you dont have to useParams you have prop with product id

2022-03-04 09:04 UTC, dblach-intive requested changes
you need to add new route product/edit/id - id its a id of product

2022-03-07 09:01 UTC, dblach-intive commented on src/components/Table/EditButton.tsx
> +import React from "react";
Can we move EditButton to components ? not inside table, we will use it in other places too, create components/EditButton catalogue with index.tsx

2022-03-07 09:55 UTC, Edyta2801 reviewed
fix

2022-03-07 10:00 UTC, dblach-intive approved these changes

2022-03-07 10:01 UTC, merged