Feature/pt 530
intive/patronage22_lublin_js_cms pull request #29
Opened 2022-03-07 15:55 UTC by FranekPoland

2022-03-08 10:28 UTC, dblach-intive requested changes

2022-03-08 10:28 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +
destructure here const {values, validateForm, errors, getFieldProps, validateForm, touched ...anything u want from formik } = formik;

2022-03-08 10:28 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +        initialValues: {
You will have here initialValues  
{ "title": "", "description": "" }

2022-03-08 10:28 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +                            value={formik.values.title}
you can use  {...props.getFieldProps('title')}
use https://github.com/intive/patronage22_lublin_js_cms/tree/main/src/components/Textfield

2022-03-08 10:28 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +                            Published: <Switch id="published"
remove published add description field {...props.getFieldProps('description')}

2022-03-08 10:28 UTC, dblach-intive commented on src/types/routes.ts
> +  ADDCATEGORY ='/addcategory',
ADD_CATEGORY

2022-03-08 10:28 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +                            <Input
Try to use TextfieldWrapper from https://github.com/intive/patronage22_lublin_js_cms/tree/main/src/components/Textfield

2022-03-08 10:28 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +                       published: formik.values.published
remove published

2022-03-10 08:58 UTC, dblach-intive requested changes

2022-03-10 08:58 UTC, dblach-intive commented on src/components/Router/Router.tsx
> +        <Route exact path={ROUTES.ADDCATEGORY} component={AuthGuard(Layout)} />
CATEGORY_ADD not ADDCATEGORY

2022-03-10 08:58 UTC, dblach-intive commented on src/components/Table/index.tsx
> +    history.replace("/addcategory");
add-category

2022-03-11 15:34 UTC, dblach-intive requested changes

2022-03-11 15:34 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +    const configTextfieldTitle = {
why you did that this way ?

2022-03-11 15:34 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +    const configTextfieldDescription = {
why you did that this way ?

2022-03-11 15:34 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +    if (formik.touched.title && Boolean(formik.errors.title)) {
what is this for ?

2022-03-11 15:34 UTC, dblach-intive commented on src/components/Table/index.tsx
> +      <Button variant="contained" style={{float:'right'}} onClick={()=> handleOnClick()}>Add Category</Button>
why did u add button here ? add this in dashboard like products button

2022-03-14 08:51 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +        onChange: formik.handleChange,
use getFieldProps

2022-03-14 08:51 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +        onChange: formik.handleChange,
use getFieldProps

2022-03-14 10:29 UTC, FranekPoland commented on src/components/CategoryForm/index.tsx
> +        initialValues: {
![image](https://user-images.githubusercontent.com/25031048/158154383-ed043535-efa6-4622-a878-86c7c1f65579.png)

You mean something like this?

2022-03-15 07:39 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +    const history = useHistory();
hooks should be placed on top

2022-03-15 07:39 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +                    {...getFieldProps('title')}></TextField>
close tag `<TextField ...... />`

2022-03-15 07:39 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +
destructurization here

2022-03-15 07:39 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +const style = {
can we add styles into separate css module ?

2022-03-15 14:32 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +                    id="description"
do we need id ?

2022-03-15 14:32 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +                    id="title"
do we need id ?

2022-03-15 14:32 UTC, dblach-intive commented on src/components/CategoryForm/index.tsx
> +import classes from '../CategoryForm/CategoryForm.module.css';
styles not classes

2022-03-16 13:01 UTC, dblach-intive approved these changes

2022-03-16 13:30 UTC, closed without merging