feature/PT-419
intive/patronage22_lublin_js_cms pull request #3
Opened 2022-02-04 14:18 UTC by Misiorny

feat: add navigation 
fix: path home

2022-02-07 09:30 UTC, dblach-intive requested changes

2022-02-07 09:30 UTC, dblach-intive commented on src/components/Navigation/NavItem.tsx
> +        <li >
Why you dont use ListItem from chakra ?

2022-02-07 09:30 UTC, dblach-intive commented on src/components/Navigation/dataLinks.tsx
> +    { id:1, to: '/dashboard', label: 'Home'},
you can use defined links from routes.ts

2022-02-07 09:30 UTC, dblach-intive commented on src/components/Navigation/dataLinks.tsx
> +const dataLinks = [
dataLinks array should be in different file for example in exsisitng routes.ts, and change the name for example menuLinks

2022-02-07 09:30 UTC, dblach-intive commented on src/components/Navigation/index.tsx
> +import Navbar from "./Navbar";
you can put all code in this place so index.tsx should contain all from Navbar.tsx

2022-02-07 09:30 UTC, dblach-intive commented on src/components/Navigation/NavItemsList.tsx
> +        <Menu >
remove white space at the end

2022-02-07 09:30 UTC, dblach-intive commented on src/components/Navigation/NavItemsList.tsx
> +        </Menu >
remove white space at the end

2022-02-07 10:31 UTC, dblach-intive commented
all changes form Pr should be in separate commit

2022-02-08 09:16 UTC, Misiorny commented on src/components/Navigation/NavItem.tsx
> +        <li >
ListItem or List? With ListItem doesn't work properly.

2022-02-09 08:59 UTC, dblach-intive requested changes

2022-02-09 08:59 UTC, dblach-intive commented on src/types/routes.ts
> +    { id:1, to: '/dashboard', label: 'Home'},
You can use ROUTES to define links, add missed links inro Routes too

2022-02-09 08:59 UTC, dblach-intive commented on src/components/Navigation/NavItem.tsx
> +function NavItem(state:
Add type for NavItem, i saw it in Patryk review ready to paste

2022-02-09 08:59 UTC, dblach-intive commented on src/components/Menu/Menu.tsx
>  import React from "react";
This file should be index.tsx not Menu.tsx

2022-02-09 09:03 UTC, dblach-intive requested changes

2022-02-09 09:03 UTC, dblach-intive commented on src/components/Navigation/NavItem.tsx
> +        <List >
This is wrong component it creates UL on every element why dont you use these elements ?
Menu,
  MenuButton,
  MenuList,
  MenuItem,
  MenuItemOption,
  MenuGroup,
  MenuOptionGroup,
  MenuDivider,

2022-02-09 15:42 UTC, Misiorny commented on src/components/Menu/Menu.tsx
>  import React from "react";
Sorry but into Menu.tsx ( not mine component but layout component) I put only Navbar component for install navigation in proper place.

2022-02-09 19:25 UTC, Misiorny commented on src/components/Navigation/NavItem.tsx
> +        <List >
Now structure will be Menu->MenuItem->Link

2022-02-16 09:41 UTC, dblach-intive commented on src/components/Navigation/dataLinks.tsx
> +    { id:1, to: '/dashboard', label: 'Home'},
yes

2022-02-17 16:05 UTC, merged