Feature/pt 1306
intive/patronage22_lublin_js_cms pull request #35
Opened 2022-03-15 16:53 UTC by kamilszalast

I change out Table component to work with any kind of data.
I'm waiting for feedback.

2022-03-17 09:30 UTC, dblach-intive requested changes

2022-03-17 09:30 UTC, dblach-intive commented on src/components/Layout/index.tsx
> +          <Route exact path='/category' render={() => <Categories />} />
categories

2022-03-17 09:30 UTC, dblach-intive commented on src/components/Table/CustomTableHead.tsx
> -import React from 'react';
remove this file from this PR you're not changing anything here

2022-03-17 09:30 UTC, dblach-intive commented on src/components/Table/index.tsx
> -import React, { useState, useMemo } from 'react';
remove this file from this PR you're not changing anything here

2022-03-17 09:30 UTC, dblach-intive commented on src/types/table.ts
> +  row: any;
use correct type

2022-03-17 09:30 UTC, dblach-intive commented on src/types/table.ts
> +  data: any;
use correct type

2022-03-17 16:12 UTC, kamilszalast commented on src/components/Table/index.tsx
> -import React, { useState, useMemo } from 'react';
I changed the interface type of Product to any, otherwise we could not use this table with rows other than product rows.

2022-03-17 16:14 UTC, kamilszalast commented on src/types/table.ts
> +  row: any;
I don't know how to change in other way. If I put Product in this place, later I got errors of wrong type assignation when I use thic CustomTable to make table of Categories.

2022-03-18 14:01 UTC, dblach-intive commented on src/components/Table/CustomTableHead.tsx
> +  const createSortHandler = (property: any) => (event: MouseEvent<unknown>) => {
type here do not use any

2022-03-18 14:02 UTC, dblach-intive commented on src/components/Table/index.tsx
> +  const [orderBy, setOrderBy] = useState<any>("id");
dont use any add correct types here

2022-03-18 14:03 UTC, dblach-intive commented on src/types/table.ts
> +  row: any;
add Products | Categories etx

2022-03-18 14:03 UTC, dblach-intive commented on src/types/table.ts
> +  data: any;
add Products | Categories etx

2022-03-18 14:29 UTC, kamilszalast commented
I corrected mistakes with the 'any' type

2022-03-18 14:47 UTC, kamilszalast commented on src/components/Layout/index.tsx
> +          <Route exact path='/category' render={() => <Categories />} />
Changed it

2022-03-18 14:48 UTC, kamilszalast commented on src/types/table.ts
> +  row: any;
added as suggested

2022-03-18 14:49 UTC, kamilszalast commented on src/types/table.ts
> +  data: any;
done

2022-03-18 14:49 UTC, kamilszalast commented on src/components/Table/CustomTableHead.tsx
> +  const createSortHandler = (property: any) => (event: MouseEvent<unknown>) => {
done

2022-03-18 14:52 UTC, kamilszalast commented
Reviewed one again, all of the 'any' types replaced with the correct ones like Product | Category etc

2022-03-18 14:55 UTC, dblach-intive approved these changes

2022-03-18 15:00 UTC, merged