Feature/pt 1307
intive/patronage22_lublin_js_cms pull request #36
Opened 2022-03-15 20:23 UTC by kamilszalast

2022-03-17 09:28 UTC, dblach-intive requested changes

2022-03-17 09:28 UTC, dblach-intive commented on src/components/Table/CategoryRow/index.tsx
> +        <EditButton id={id} nameOfEditingItem={"category"}>
what is this for ? nameOfEditingItem ? this name is wrong, and we dont need this props here

2022-03-17 09:28 UTC, dblach-intive commented on src/components/Table/index.tsx
> -import React, { useState, useMemo } from 'react';
remove this file from this PR you're not changing anything here

2022-03-17 09:28 UTC, dblach-intive commented on src/components/Table/ProductRow/index.tsx
> -import { Chip } from '@mui/material';
remove this file from this PR you're not changing anything here

2022-03-17 09:28 UTC, dblach-intive commented on src/components/Table/CustomTableHead.tsx
> -import React from 'react';
remove this file from this PR you're not changing anything here

2022-03-18 13:18 UTC, kamilszalast commented on src/components/Table/CategoryRow/index.tsx
> +        <EditButton id={id} nameOfEditingItem={"category"}>
I change EditButton to extend this usability, because in previous version we can only edit products with this button. Sholud I make another button to edit only categories?

2022-03-18 14:37 UTC, closed without merging