feat: add OrderDerails page with mocked data, add DataGrid dependency
intive/patronage22_lublin_js_cms pull request #64
Opened 2022-04-09 14:49 UTC by kamilszalast

2022-04-09 15:03 UTC, kamilszalast commented
I add OrderDerails page, with mocked data. If everything is ok, I try to get data prom API

2022-04-11 14:00 UTC, dblach-intive requested changes

2022-04-11 14:00 UTC, dblach-intive commented on src/pages/OrderDetails.tsx
> +import { DataGrid } from "@mui/x-data-grid";
We can use our Table component

2022-04-11 14:00 UTC, dblach-intive commented on src/pages/OrderDetails.tsx
> +const setOrderDetailRows = (
Create separate row for order just like we used it everywhere

2022-04-11 14:00 UTC, dblach-intive commented on src/pages/OrderDetails.tsx
> +        columns={[
use our Table component and put these kind of data as a props from parent

2022-04-11 14:00 UTC, dblach-intive commented on package.json
> +    "@mui/x-data-grid": "^5.8.0",
we have table component

2022-04-11 14:00 UTC, dblach-intive commented on src/pages/OrderDetails.tsx
> +  const detailRows = setOrderDetailRows(mockedOrderDetails, apiProducts, id);
u can use useMemo, btw if we're using parsers like this u can just create utils/index.ts and there u can keep any parsers or helpers setOrderDetailRows

2022-04-15 11:55 UTC, dblach-intive commented on package.json
> +    "@mui/x-data-grid": "^5.8.0",
we should remove this one

2022-04-15 12:46 UTC, kamilszalast commented on package.json
> +    "@mui/x-data-grid": "^5.8.0",
removed

2022-04-15 13:09 UTC, merged